### ISSUE TITLE
Understanding the results

### ISSUE THREAD

**Issue by artcg** [Nadr0j/MovingSofa#1]
Hi, I just wanted to clarify

I think what your algorithm does:

- Finds a polygon solution which resembles the Gerver sofa, but does _not prove_ that it is an upper bound

Or, on the contrary, does it prove that your approximation is an upper bound (and in that case the wikipedia article needs to be updated)

Best regards,
Arthur

**Comment by Nadr0j** [comment]
Hi Arthur,

It does not prove that the approximation is an upper bound on the solution(s) to the problem.

Best,
Jordan

**Comment by artcg** [comment]
Thanks for the clarification, may try some experimentations in that direction myself, though it seems like it may be more difficult to get a result than it looks
